### ISSUE TITLE
How long will you finish?

### ISSUE THREAD

**Issue by Lvjunqiao** [stalern/SpikeSystem#1]
I have konwn that you want to finish a high concurrency system. Can you share your rough idea about your project ? I  have developed an interest in  your project. And also , if you can answer the question of the title ,it will be very nice .

**Comment by stalern** [comment]
Thanks for your following about my pro. It's just a whole and very rough arthitecture. Maybe i will finish the program and doc in this week. I would be appreciate for your concern and it's my honor to listen your idea about the pro.
your sincerely
